[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://lostcryptohelp.pro"

  # 🔐 External APIs
  ETHERSCAN_API_KEY = "${ETHERSCAN_API_KEY}"
  BSCSCAN_API_KEY = "${BSCSCAN_API_KEY}"
  TRONSCAN_API_KEY = "${TRONSCAN_API_KEY}"

  # 📬 Telegram Bot
  VITE_TELEGRAM_BOT_TOKEN = "${VITE_TELEGRAM_BOT_TOKEN}"
  VITE_TELEGRAM_CHAT_ID = "${VITE_TELEGRAM_CHAT_ID}"

  # ✅ Verification Wallets
  VERIFY_ETH_ADDRESS = "${VERIFY_ETH_ADDRESS}"
  VERIFY_BNB_ADDRESS = "${VERIFY_BNB_ADDRESS}"
  VERIFY_TRON_ADDRESS = "${VERIFY_TRON_ADDRESS}"
